### ISSUE TITLE
localhost cert needs to be regenerated for Chrome 58+

### ISSUE THREAD

**Issue by keith** [stewart/dotcss#23]
As of Chrome 58, the certificate used in dotcss is no longer valid. See [this issue](https://github.com/webpack/webpack-dev-server/issues/854) for details. In order to fix this the cert in dotcss (and dotjs) must be replaced with a new cert generated with [this command](https://github.com/webpack/webpack-dev-server/issues/854#issuecomment-292445914) to work on macOS:

```sh
openssl req \
    -newkey rsa:2048 \
    -x509 \
    -nodes \
    -keyout server.pem \
    -new \
    -out server.pem \
    -subj /CN=localhost \
    -reqexts SAN \
    -extensions SAN \
    -config <(cat /System/Library/OpenSSL/openssl.cnf \
        <(printf '[SAN]\nsubjectAltName=DNS:localhost')) \
    -sha256 \
    -days 3650
```

I've successfully regenerated this cert and reinstall dotcss, but I feel like the owner of this project should be the one to update something this sensitive.

**Comment by stewart** [comment]
Thanks for reporting, I've regenerated the cert.

**Comment by keith** [comment]
It works thanks!!
